#!/bin/bash
REPO_PATH="$(dirname "${BASH_SOURCE[0]}")"
DUMP="$(type realpath 2>&1)"
export REPO_PATH
SEP=":"
if [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "win32" ]]; then
    SEP=";"
fi
export PYTHONPATH="$PYTHONPATH$SEP$REPO_PATH"
python3 "$REPO_PATH/yapenv" "$@"
